add_library(glad ${CMAKE_CURRENT_LIST_DIR}/../external/glad/glad.c)

add_library(apeiron
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/camera.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/camera.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/collision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/collision.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/color_converter.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/entity.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/error.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/event.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/input.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/image_loader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/image_loader.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/model_loader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/model_loader.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/primitive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/primitive.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/transform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/transform.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/text.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/engine/vertex.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/cuboid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/cuboid.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/cylinder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/cylinder.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/frame_buffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/frame_buffer.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/grid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/grid.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/mesh_font.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/mesh_font.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/meshset.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/meshset.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/model.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/points.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/points.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/quad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/quad.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/renderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/renderer.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/shader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/shader.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/shape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/shape.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/texture.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/texture.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/tileset.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/tileset.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/triangles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/triangles.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/wire_cuboid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/opengl/wire_cuboid.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/prefab/axis.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/prefab/axes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/prefab/axes.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/prefab/grid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/prefab/grid.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/prefab/light.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/prefab/teapot.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/utility/linear_range.h
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/utility/timer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../apeiron/utility/timer.h)

list(APPEND APEIRON_INCLUDE_DIRECTORIES
    ${CMAKE_CURRENT_LIST_DIR}/../external
    ${CMAKE_CURRENT_LIST_DIR}/../external/glm
    ${CMAKE_CURRENT_LIST_DIR}/../external/glad)

include_directories(${APEIRON_INCLUDE_DIRECTORIES})
target_link_libraries(apeiron glad)
